version: '3'
services:
  frontend:
    container_name: frontend
    tty: true
    image: node:17-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports:
      - '3000:3000'
